### ISSUE TITLE
How to use ref

### ISSUE THREAD

**Issue by matthughes** [chandu0101/scalajs-react-components#2]
Trying to replace:

```
input(ref := "newTask")(onchange ==> b.processTask)(placeholder := "What needs to be done?")
```

with bootStrap input but I can't figure out where you would add that variable?  Am I missing it or it's just not there yet?

**Comment by matthughes** [comment]
I'm starting to think there is something wrong with this approach at least when it comes to React components that are essentially subclasses of HTML elements.

scalajs-react/scalatags don't try to type every attribute possible/required for every HTML element.  They let you write something nonsensical like the following:

`table(`type` := "text")`

Why should mapping third party components be any different?  In addition to missing "ref", the component is also missing all the attributes listed here:

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Input and here:
https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes

I certainly understand wanted to add type-safety and I would even argue to make required elements typed, but there are just too many possible attributes to list them all.

@japgolly Do you have any thoughts on this?

**Comment by chandu0101** [comment]
@matthughes  without going to details , don't use these wrappers , intrerop with purejs is not working quite well , we must port to scala.js-react. I am waiting on this issue https://github.com/japgolly/scalajs-react/issues/44 to start porting components , once that issue resolved , my todo list is material UI then bootstrap . 

Thank You
Chandra

**Comment by japgolly** [comment]
Mornings boys.

I do indeed have thoughts :) They point in opposing directions unfortunately.
- Bootstrap components are composites. You could return the top-most node as a scalatag so that you can continue to modify it, but you still wouldn't be able to modify its bootstrappy children. eg. if a bootstrap component is `div(p(..))` how would you be able to modify the p? Would you want to? I _do_ think it would be important to be able to at least modify the outmost `div`.
- I like scalatags giving me lots of freedom because I know html & css. Bootstrap I don't know as well so I think I'd appreciate that extra type guidance.
- Taking a step back, I like the idea that with React components I should be able to say "I want that component here!" and there's a contract of required and optional data (its _props_) you specify to make it work and customise it, without me having to care about how its built.... But I feel that there are going to be hidden issues there, I think you're discovering one now Matt. I'd say once we understand what hidden issues to expect and their extent we'll be in a better position to decide if React components with typed attributes are optimal and/or worth any tradeoffs.
- Don't forget one can always cheaply experiment with alternatives. Typed Scala functions seem to work just as well for small components. Like `def bootstrapButton(lbl: String) = div(cls := "outer", div(lbl))`.

And Chandy, yep that issue is on my mental list. Shouldn't be too long now :)
