### ISSUE TITLE
onKeyDown / onKeyUp / etc missing on MuiTextField (and others?)

### ISSUE THREAD

**Issue by codingismy11to7** [chandu0101/scalajs-react-components#83]
The material-ui library stopped documenting that `onKeyDown` (for instance) is on a `TextField` (for instance).

They have this issue: https://github.com/callemall/material-ui/issues/6001
Which links to this react doc page: https://facebook.github.io/react/docs/events.html#keyboard-events
And that issue says:

> Yes, synthetic events are props you can attach to any React component.

I'm a little out of my knowledge area here, but after copying `MuiTextField` and adding a `onKeyDown: js.UndefOr[ReactKeyboardEventI ⇒ Callback] = js.undefined,` field, I'm able to catch keyboard events again in 0.6.0 (using material-ui 0.17.4)

**Comment by oyvindberg** [comment]
Yeah, this is a bit unfortunate. Our current Scala encoding of react components doesn't include general DOM event handlers for instance, and that makes them rather inflexible. I have been planning to explore other encodings, for example with traits so you can inherit all those things, but i haven't had time. I generated all the DOM event handlers in #73, but didn't like it since we were drowning in parameters.

 Alternatively just providing an escape hatch where you pass `Map[String, js.Any]` would be practical. 

Make local copies of the components where needed for now and adapt them, and we'll get back to this :)

**Comment by trepidacious** [comment]
Is there any news on this? I just ran into the same thing and it took me a good hour to track down then another to get a new facade working with onKeyPress included for TextField. I was thinking that even if this won't be fixed, it could be documented in the `Gotchas` on main page?

I'm pretty hazy on how the facades are generated, etc., but would it be possible to add a slight hack to the existing generation system to add some hand-picked things like this? Seems key presses on TextField are so common that they could be a special case.

**Comment by rleibman** [comment]
I just checked the 1.x versions that we're working on, the standard input callbacks are there. So I think we can close this issue.
